#!/usr/bin/env python3
"""context-tax CLI — show where coding agents will burn context tokens."""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from . import __version__
from .audit import audit, suggest_agentignore, cost_usd, result_to_dict


def _fmt_int(n: int) -> str:
    return f"{n:,}"


def _fmt_bytes(n: int) -> str:
    if n < 1024:
        return f"{n} B"
    if n < 1024**2:
        return f"{n/1024:.1f} KB"
    if n < 1024**3:
        return f"{n/1024**2:.2f} MB"
    return f"{n/1024**3:.2f} GB"


def _respect_gitignore(args: argparse.Namespace) -> bool:
    """--no-ignore is the blanket opt-out; it overrides --respect-gitignore."""
    return args.respect_gitignore and not args.no_ignore


def cmd_scan(root: Path, args: argparse.Namespace) -> int:
    result = audit(
        root,
        max_file_bytes=args.max_file_mb * 1024 * 1024,
        follow_ignores=not args.no_ignore,
        respect_gitignore=_respect_gitignore(args),
    )

    if args.json:
        payload = result_to_dict(result)
        if args.price is not None:
            payload["est_cost_usd_full_dump"] = cost_usd(result.total_tokens_est, args.price)
            payload["usd_per_mtok"] = args.price
        print(json.dumps(payload, indent=2))
        return 0

    print(f"context-tax v{__version__}")
    print(f"root:    {result.root}")
    print(
        f"scanned: {_fmt_int(len(result.files))} files  |  "
        f"{_fmt_bytes(result.total_bytes)}  |  "
        f"~{_fmt_int(result.total_tokens_est)} tokens (est.)"
    )
    if args.price is not None:
        c = cost_usd(result.total_tokens_est, args.price)
        print(
            f"cost*:   ~${c:.4f} if an agent ingested everything "
            f"(at ${args.price}/M input tokens) — illustrative only"
        )
    print()

    print("By category")
    print(f"{'category':12} {'files':>8} {'size':>12} {'~tokens':>12}")
    cats = sorted(result.by_category.items(), key=lambda kv: -kv[1]["tokens_est"])
    for name, s in cats:
        print(
            f"{name:12} {s['files']:>8} {_fmt_bytes(s['bytes']):>12} {_fmt_int(s['tokens_est']):>12}"
        )
    print()

    print(f"Top {args.top} files by estimated tokens")
    print(f"{'~tokens':>10}  {'size':>10}  {'cat':10}  path")
    for f in result.files[: args.top]:
        print(
            f"{_fmt_int(f.tokens_est):>10}  {_fmt_bytes(f.bytes):>10}  {f.category:10}  {f.path}"
        )
    print()

    if result.skipped_dirs_hit:
        hits = sorted(result.skipped_dirs_hit.items(), key=lambda kv: -kv[1])[:12]
        print("Skipped dir names (default + ignore rules):")
        print("  " + ", ".join(f"{k}×{v}" for k, v in hits))
        print()

    if result.ignored_by_rules:
        label = ".agentignore + .gitignore" if _respect_gitignore(args) else ".agentignore"
        print(f"Ignore rules ({label}) excluded {_fmt_int(result.ignored_by_rules)} paths.")
        print()

    # Advice
    locks = result.by_category.get("lockfile", {}).get("tokens_est", 0)
    binary = result.by_category.get("binary", {}).get("tokens_est", 0)
    gen = result.by_category.get("generated", {}).get("tokens_est", 0)
    src = result.by_category.get("source", {}).get("tokens_est", 0)
    print("Read this")
    print(f"  • Source is ~{_fmt_int(src)} tokens — protect this; it's the useful map.")
    if locks:
        print(
            f"  • Lockfiles alone are ~{_fmt_int(locks)} tokens. "
            "Almost never useful inside an agent prompt — ignore them."
        )
    if binary or gen:
        print(
            f"  • Binary+generated ~{_fmt_int(binary + gen)} tokens. "
            "Don't let agents open these."
        )
    if result.total_tokens_est > 200_000:
        print(
            "  • Full-tree dump exceeds a 200k context window estimate. "
            "Use AGENTS.md + path-scoped reads (see repo-harness)."
        )
    elif result.total_tokens_est > 100_000:
        print(
            "  • Large repo: prefer architecture TOC + targeted file reads over whole-tree paste."
        )
    print()
    print("Tokens are rough estimates (chars/4 for text). Good for ranking, not billing.")
    return 0


def cmd_suggest(root: Path, args: argparse.Namespace) -> int:
    result = audit(
        root,
        follow_ignores=not args.no_ignore,
        respect_gitignore=_respect_gitignore(args),
    )
    lines = suggest_agentignore(result, top_n=args.top)
    header = [
        "# Suggested .agentignore additions (generated by context-tax)",
        f"# root: {result.root}",
        f"# ~tokens scanned (non-skipped): {result.total_tokens_est}",
        "",
        "# --- defaults you likely already skip ---",
        "node_modules/",
        ".git/",
        ".venv/",
        "dist/",
        "build/",
        "target/",
        "__pycache__/",
        "",
    ]
    text = "\n".join(header + lines) + "\n"
    if args.write:
        out = root / ".agentignore"
        if out.exists() and not args.force:
            # append unique
            existing = out.read_text(encoding="utf-8", errors="replace")
            additions = [ln for ln in (header + lines) if ln and not ln.startswith("#") and ln not in existing]
            if additions:
                with out.open("a", encoding="utf-8") as fh:
                    fh.write("\n# --- context-tax append ---\n")
                    fh.write("\n".join(additions) + "\n")
                print(f"appended {len(additions)} lines → {out}")
            else:
                print(f"no new lines to append → {out}")
        else:
            out.write_text(text, encoding="utf-8")
            print(f"wrote {out}")
    else:
        sys.stdout.write(text)
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="context-tax",
        description=(
            "Audit a repository for coding-agent context cost: "
            "which files dominate token estimates and what to ignore."
        ),
    )
    parser.add_argument("--version", action="version", version=f"%(prog)s {__version__}")
    sub = parser.add_subparsers(dest="cmd", required=True)

    def add_common(p: argparse.ArgumentParser) -> None:
        p.add_argument("-C", "--directory", default=".", help="Repo root (default: .)")
        p.add_argument(
            "--no-ignore",
            action="store_true",
            help="Do not honor any .agentignore/.gitignore rules",
        )
        p.add_argument(
            "--respect-gitignore",
            action=argparse.BooleanOptionalAction,
            default=True,
            help="Honor .gitignore rules, nested ones included (default: on)",
        )
        p.add_argument(
            "--max-file-mb",
            type=int,
            default=5,
            help="Max file size to fully read (default: 5)",
        )

    p_scan = sub.add_parser("scan", help="Print token tax report")
    add_common(p_scan)
    p_scan.add_argument("--top", type=int, default=25, help="Top N files (default 25)")
    p_scan.add_argument("--json", action="store_true", help="JSON output")
    p_scan.add_argument(
        "--price",
        type=float,
        default=None,
        metavar="USD_PER_MTOK",
        help="Optional $/M input tokens for illustrative full-dump cost",
    )

    p_sug = sub.add_parser("suggest-ignore", help="Suggest .agentignore entries")
    add_common(p_sug)
    p_sug.add_argument("--top", type=int, default=40)
    p_sug.add_argument("--write", action="store_true", help="Write/append .agentignore")
    p_sug.add_argument("--force", action="store_true", help="Overwrite .agentignore")

    args = parser.parse_args(argv)
    root = Path(args.directory).resolve()
    if not root.is_dir():
        print(f"error: not a directory: {root}", file=sys.stderr)
        return 2

    if args.cmd == "scan":
        return cmd_scan(root, args)
    if args.cmd == "suggest-ignore":
        return cmd_suggest(root, args)
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
